import { promises as fs } from "node:fs";
import { join } from "node:path";

import type { ConfigContext, ExpoConfig } from "expo/config";
import { withDangerousMod, withXcodeProject } from "expo/config-plugins";

const VERSION = "1.0.0";
const IOS_IN_APP_PURCHASE_CAPABILITY = "com.apple.InAppPurchase";
const GRADLE_DAEMON_JVM_FILE_HEADER = "#This file is generated by app.config.ts";
const GRADLE_DAEMON_JVM_FILE_CONTENT = `${GRADLE_DAEMON_JVM_FILE_HEADER}
toolchainVersion=21
`;

function withIosInAppPurchaseCapability(config: ExpoConfig) {
  return withXcodeProject(config, (mod) => {
    const project = mod.modResults;
    const target = project.getFirstTarget();

    if (!target) {
      return mod;
    }

    const attributes = project.getFirstProject().firstProject.attributes as {
      TargetAttributes?: Record<
        string,
        {
          SystemCapabilities?: Record<string, { enabled: number }>;
        }
      >;
    };
    const targetAttributes = (attributes.TargetAttributes ??= {});
    const capabilityAttributes = (targetAttributes[target.uuid] ??= {});
    const systemCapabilities = (capabilityAttributes.SystemCapabilities ??= {});

    // Standard StoreKit in-app purchases are a target capability, not an entitlements plist key.
    systemCapabilities[IOS_IN_APP_PURCHASE_CAPABILITY] = { enabled: 1 };

    return mod;
  });
}

function withAndroidGradleDaemonJvmPin(config: ExpoConfig) {
  return withDangerousMod(config, [
    "android",
    async (mod) => {
      const gradleDir = join(mod.modRequest.platformProjectRoot, "gradle");
      const gradleDaemonJvmFilePath = join(gradleDir, "gradle-daemon-jvm.properties");

      await fs.mkdir(gradleDir, { recursive: true });
      await fs.writeFile(
        gradleDaemonJvmFilePath,
        GRADLE_DAEMON_JVM_FILE_CONTENT,
        "utf8",
      );

      return mod;
    },
  ]);
}

export default function getConfig({ config }: ConfigContext): ExpoConfig {
  return withAndroidGradleDaemonJvmPin(
    withIosInAppPurchaseCapability({
      ...config,
      name: "File Transfers",
      slug: "file-transfers",
      version: VERSION,
      icon: "./assets/icon.png",
      orientation: "portrait",
      scheme: "filetransfers",
      userInterfaceStyle: "light",
      ios: {
        ...config.ios,
        supportsTablet: false,
        usesAppleSignIn: true,
        bundleIdentifier: "com.jonluca.filetransfers",
        infoPlist: {
          ITSAppUsesNonExemptEncryption: false,
          NSCameraUsageDescription: "Scan a nearby device QR code to connect to a transfer.",
          NSLocalNetworkUsageDescription:
            "Discover nearby devices on your local WiFi so files can transfer directly.",
          NSBonjourServices: ["_filetransfer._tcp."],
        },
      },
      android: {
        ...config.android,
        package: "com.jonluca.filetransfers",
        predictiveBackGestureEnabled: false,
        permissions: [
          "android.permission.INTERNET",
          "android.permission.ACCESS_FINE_LOCATION",
          "android.permission.ACCESS_NETWORK_STATE",
          "android.permission.ACCESS_WIFI_STATE",
          "android.permission.CHANGE_WIFI_MULTICAST_STATE",
          "android.permission.CAMERA",
        ],
      },
      plugins: [
        ...(config.plugins ?? []),
        "expo-apple-authentication",
        "expo-router",
        "expo-web-browser",
        "expo-sqlite",
        [
          "expo-camera",
          {
            cameraPermission: "Scan a nearby device QR code to join a transfer session.",
          },
        ],
        [
          "expo-build-properties",
          {
            android: {
              minSdkVersion: 28,
            },
          },
        ],
        [
          "expo-document-picker",
          {
            iCloudContainerEnvironment: "Production",
          },
        ],
      ],
      experiments: {
        typedRoutes: true,
        reactCompiler: true,
      },
      extra: {
        router: {},
        eas: {
          projectId: "1070ca5a-5d8a-48ee-a705-b039eccc579b",
        },
      },
    } satisfies ExpoConfig),
  );
}
